= Red Hat Data Grid 8 Authorization Playground
Álvaro López Medina <alopezme@redhat.com>
v1.0, 2022-11
// Metadata
:description: This document shows how to perform basic installations of Red Hat Data Grid customizing its configuration.
:keywords: infinispan, datagrid, openshift, red hat
// Create TOC wherever needed
:toc: macro
:sectanchors:
:sectnumlevels: 2
:sectnums: 
:source-highlighter: pygments
:imagesdir: images
// Start: Enable admonition icons
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
ifndef::env-github[]
:icons: font
endif::[]

// Create the Table of contents here
toc::[]

== Roles and permissions

This repository tries to understand how to set the correct roles and permissions to cache and CacheManager to achieve soft-multitenancy.

In this case, we have two teams: `Products` and `Discounts`. Each of them has one microservice and two caches. 

Cache access should be as follows:

* discounts-01: `Discounts` has read-write permission and `Products` has read.
* discounts-02: `Discounts` has read-write permission and `Products` has none.
* products-01: `Products` has read-write permission and `Discounts` has read.
* products-02: `Products` has read-write permission and `Discounts` has none.

== How to deploy on OCP?

Install the operator and then execute the following commands:

1. Create a secret based on the `identities.yaml` file:
+
[source, bash]
----
oc create secret generic --from-file=identities.yaml dg-cluster-credentials
----
+
2. Create the rest of the resources:
+
[source, bash]
----
oc apply -f cluster.yaml
----

This will create the following objects:

[source, console]
----
cache.infinispan.org/dg-cluster-rhdg.examples.discounts-01
cache.infinispan.org/dg-cluster-rhdg.examples.discounts-02
cache.infinispan.org/dg-cluster-rhdg.examples.products-01
cache.infinispan.org/dg-cluster-rhdg.examples.products-02
infinispan.infinispan.org/dg-cluster
secret/dg-cluster-credentials
route.route.openshift.io/dg-cluster
----

