kind: Cache
apiVersion: infinispan.org/v2alpha1
metadata:
  name: dg-cluster-rhdg-examples-products-02
  labels:
    app: dg-cluster-datagrid
spec:
  clusterName: dg-cluster
  name: rhdg-examples-products-02
  template: |
    distributedCache:
      encoding:
        key:
          mediaType: application/x-protostream
        value:
          mediaType: application/x-protostream
      expiration:
        lifespan: "3600000"
        maxIdle: "-1"
      memory:
        maxSize: 500MB
        whenFull: REMOVE
      mode: SYNC
      owners: "1"
      security:
        authorization:
          enabled: true
          roles:
          - products-write
          - products-read
          - monitor
      statistics: "true"